name = "ellipse"
description = "Draws an ellipse on to the screen."
isScreen = true
parameters = [ "x", "y", "radiusX", "radiusY", "fillColor" ]
pdata = [
	"Horizontal coordiante.",
	"Vertical coordinate.",
	"Horizontal radius.",
	"Vertical radius",
	"[OPTIONAL]. Fill color for the ellipse."
]
seeAlso = [
	"arc", "bezier", "circle", "draw", "line", "rect", "paint", "point", "pset", "setColor"
]
category = "primatives"
example = """
$.screen("300x200");
$.ellipse(150, 100, 50, 80, "blue");"""
