name = "getPosPx"
description = """Gets the position of the print cursor and returns the coordinates. The data
returned is an object containing a row and a column. Example: { x: 5, y: 5 }. The x
and y coordinates are based on top left corner pixel position of the print cursor."""
isScreen = true
parameters = [ ]
seeAlso = [ "getPos", "print", "setPos", "setPosPx" ]
category = "print"
returns = "An object containing the pixel coordinates of the print cursor."
example = """
$.screen("300x200");
$.setPosPx(15, 15);
var pos = $.getPosPx();
$.print(pos.x + ", " + pos.y);
"""