name = "ontouch"
description = """
Create a touch event.
"""
isScreen = true
parameters = [ "mode", "fn", "once", "hitBox", "customData" ]
pdata = [
	"The type of touch event. Must be a string value set to start, end, or move.",
	"The function to called when touch occurs. The first parameter will contain the touches data.",
	"[OPTIONAL]. A boolean if true deletes the event after being called one time.",
	"[OPTIONAL]. A hitBox to restrict events occuring outside the box",
	"""[OPTIONAL]. This can be used to assign data that will be passed into the callback event. \
		This is useful if you have multiple onmouse commands that use the same callback function."""
]
seeAlso = [ "clearEvents", "intouch", "offtouch", "setPinchZoom", "startTouch", "stopTouch" ]
category = "touch"
example = """
$.screen( "4x4" );
$.setPinchZoom( false );
$.ontouch( "start", function ( touches ) {
	var touch = touches[ 0 ];
	$.setColor( Math.floor( Math.random() * 9 ) + 1 );
	$.pset( touch.x, touch.y );
} );
"""
