name = "paint"
isScreen = true
parameters = [ "x", "y", "fillColor", "tolerance" ]
description = "Fills in areas of the screen that are the same color."
pdata = [
	"The horizontal coordinate from where to start the paint algorithm.",
	"The vertical coordinate from where to start the paint algorithm.",
	"The fill color.",
	"""[OPTIONAL]. A number between 0 and 1 that allows you to set how sensitive the algorithm is\
		to color differences."""
]
seeAlso = [
	"arc", "bezier", "circle", "draw", "ellipse", "line", "point", "pset", "rect", "setColor"
]
category = "primatives"
example = """
var color = [ 255, 255, 255 ];
var color2 = [ 25, 85, 125 ];
$.screen( "256x256" );
$.setColor( 15 );
$.setPen( "pixel", 1, 100 );
for( i = 0; i < 128; i++ ) {
	color[ 0 ] -= 2;
	color[ 1 ] -= 2;
	color[ 2 ] -= 2;
	$.setColor( color );
	$.rect( i, i, 255 - i * 2 + 1, 255 - i * 2 + 1 );
}
$.setPen( "pixel", 1 );
$.print( "Click screen to paint" );
$.onclick( function ( mouse ) {
	$.paint( mouse.x, mouse.y, color2, 0.75 );
} );
"""