name = "point"
isScreen = true
parameters = [ "x", "y" ]
description = "Gets the pixel color from the screen and returns the color palette index."
pdata = [ "The horizontal coordinate for the pixel", "The vertical coordinate for the pixel" ]
seeAlso = [
	"findColor", "get", "getPixel", "pset", "put", "setColor", "setColors"
]
returns = "The color index (integer)."
example = """
$.screen( "300x200" );
$.setColor( 5 );
$.pset( 55, 55 );
var pixel = $.point( 55, 55 );
$.print( pixel );
"""