name = "put"
description = """
Writes a 2-dimensional array of color values onto the screen. It's counterpart the get statement
will create an array of color values that you can use with the put statement. Or you can create
your own array to use.
"""
isScreen = true
parameters = [ "data", "x", "y", "includeZero" ]
pdata = [
	"The 2d array of color values.",
	"The horizontal coordinate of the starting position to write the pixels.",
	"The vertical coordinate of the starting position to write the pixels.",
	"If set to true then it will copy 0 (transparent) pixels."
]
seeAlso = [
	"get"
]
category = "primatives"
example = """
var data = [
	[  1,  2,  3,  4,  5,  6 ],
	[  7,  8,  9, 10, 11, 12 ],
	[ 13, 14, 15, 16, 17, 18 ]
]
$.screen( "30x20" );
$.put( data, 1, 1 );
"""
