name = "removeAllScreens"
description = "Removes all screens from memory and the DOM."
isScreen = false
parameters = [ ]
category = "graphics"
example = """
$.screen( "300x200" );
$.setColor( 5 );
$.rect( 25, 25, 150, 100, 2 );
$.removeAllScreens();
"""