name = "setDefaultPal"
description = "Sets the default color palette for new screens."
isScreen = false
parameters = [ "pal" ]
pdata = [ "An array of color values to use as new palette." ]
category = "color"
example = """
var colors = [
	"black", "red", "green", "blue", 
	"navy", "orange", "purple", "gray",
	"white", "pink", "brown", "cyan"
];
$.setDefaultPal( colors );
$.screen( "300x200" );
for( var i = 0; i < colors.length; i++ ) {
	$.setColor( i );
	$.print( i + " = " + colors[ i ] );
}
"""
