name = "setEnableContextMenu"
description = "Disables context menu on right click."
isScreen = true
parameters = [ "isEnabled" ]
pdata = [ "If set to true context menu will be enabled." ]
category = "mouse"
example = """
$.screen( "300x200" );
$.print( "Try right click to see if context menu appears." );
$.setEnableContextMenu( false );
"""
