name = "setVolume"
description = "Sets the master volume for all sound commands."
isScreen = false
parameters = [ "volume" ]
pdata = [ "The volume between 0 and 1 that sets the master volume." ]
seeAlso = [ "play", "playAudioPool", "sound" ]
category = "sound"
example = """
$.setVolume( 0.75 );
$.play( "Q1o3L8ED+ED+Eo2Bo3DCL2o2A" );
"""
