name = "stopKeyboard"
description = """
Stops tracking keyboard input.
"""
isScreen = false
parameters = [ ]
seeAlso = [ "inkey", "input", "onkey", "startKeyboard" ]
category = "keyboard"
example = """
$.screen( "300x200" );

var hitbox = {
	"x": 175,
	"y": 75,
	"width": 100,
	"height": 100
};
var msg = "";
var isGreen = true;

$.onclick( clickBox, false, hitbox );
$.onkey( "any", "down", function ( key ) {
	msg = "You pressed " + key.key + ".";
	drawScreen();
} );
$.onkey( "any", "up", function ( key ) {
	msg = "";
	drawScreen();
} );

drawScreen();

function drawScreen() {
	$.cls();
	$.setColor( 7 );
	$.print( "Press any key" );
	$.print( "Click the box to toggle keyboard." );
	$.print( isGreen ? "Keyboard enabled" : "Keyboard disabled" );
	$.print( msg );
	$.setColor( isGreen ? 2 : 4 );
	$.rect( hitbox );
}

function clickBox() {
	isGreen = !isGreen;
	if( isGreen ) {
		$.startKeyboard();
	} else {
		$.stopKeyboard();
	}
	drawScreen();
}
"""