name = "swapColor"
description = "Swaps a color in the screens palette with a new color and updates the screen colors."
isScreen = true
parameters = [ "oldColor", "newColor" ]
pdata = [
	"The color that needs to be swapped out.",
	"The new color."
]
seeAlso = [ "getPal", "setPalColor" ]
category = "color"
example = """
$.screen( "300x200" );
$.setColor( 2 );
$.print( "HELLO" );
$.swapColor( 2, "red" );
"""